language: python
python:
    - "3.6" 
cache: pip
before_script: 
    - easy_install distribute  
    - pip install -r requirements.txt
    - pip install pycodestyle
script:
   - pycodestyle Activity.py
   - python Activity1.py
